---
title: "Optimized Decision Making About Library Shelf Space Through Simulation"
author: "Daina Bouquin, John DeBlase, James Topor"
date: "December 5, 2016"
output: pdf_document
geometry: margin=2.2cm
---


```{r, include=FALSE, echo=FALSE, warning=FALSE}

library(ggplot2)
library(dplyr)
library(knitr)
```

# Abstract

Intro/Background sentence. Approach sentence. Findings sentence. Conclusions sentence.

#### Key Words: Library Science, Shelf Shifting, Simulation, Monte Carlo Estimation

# Introduction

Shelf shifting is the process by which free space in a library's collection can be divided up and redistributed amongst shelves to distribute books more evenly throughout the collection. "Shifting is one of the most important steps necessary to ensure that a collection is maintained in proper order while allowing room for growth" [1]. The process of shelf shifting can be done on either a small or large scale whenever major changes occur within a library's physical collection. However, it can also be required when regular collection growth results in overfilling of shelves. While regular "weeding" and "de-duplicating" (periodic processes that remove out-of-date and/or rarely circulated volumes or duplicate volumes from library shelves) can themselves somewhat alleviate the need for periodic shelf shifting, such processes are usually not sufficient to prevent a collection's shelves from becoming overfilled. As a result, many libraries have adopted off-site storage models wherein a portion of the physical collection is stored remotely and is accessed via courier or other delivery service. However, the cost of off-site storage can be substantial, as is the cost of recalling material back to the main library from the remote storage facility. Similarly, shelf-shifting can be a time consuming and expensive process when shelves are allowed to fill over long periods of time. And while there has in the recent past been a notable shift toward electronic book collecting, physical collections are still maintained. It is therefore in a library's best interest to store as little offsite as possible and to simultanerously execute shelf shifting activities as little as possible.

With this context in mind, our research attempts to answer the question:

- What is the ideal amount of space to leave empty on a book shelf to minimize the need to shelf shift while also accomodating the largest possible quantity books?

Implicit in this research question is the goal of limiting the amount of time needed to maintain the library's physical collection. For example, if a library can improve its ability to predict when a shelf shifting initiative will likely be required based on variables such as the number of books periodically added, weeded, and de-duplicated within a collection, the library might not only be able to take steps to minimize the need for shelf shifting but also more effectively plan and budget for any required shelf shifts when they do occur.

Also implicit in this question is the assumption that the library in question has access to an off-site storage option. Granular metrics for libraries having such off-site storage (typically large academic libraries) are not publicly available, nor are metrics for their individual collections generalizable; different collections in different domains housed at different institutions are subject to very individualized collection development policies that impact the basic metrics one would use to simulate various processes associated with a library's physical collections. For these reasons, the herein described simulation is to be treated as a simple case study or "proof-of-concept" based on a simulated small collection from a single library having access to an off-site storage facility. 

# Background 

The library to be used as a case example and from which metrics are drawn to create the initial set of simulation assumptions is the Wolbach Library at the Harvard-Smithsonian Center for Astrophysics in Cambridge, MA [1]. Metrics are gathered from Wolbach's Head Librarian who has access to Wolbach's in-development collection development and weeding policies, as well as circulation metrics associated with the physical collection.

The following facts are illustrative of Wolbach's practices and the benefits of using simulation to support decision making when it comes to the maintance of a physical library collection:

- __Shifting Time__: It takes one Wolbach staff person shifting at 10.87 inches of books per minute for 7 hours to shift a section of the Wolbach Collection. Due to the physical strain of this work, this sort of shift is typically split over 2 days. One can assume all staff members make at least $17/hour and that this timeframe does not take into account time needed for planning the shift. If it is necessary to shift many sections, this adds to the time significantly. Large shifts can take many weeks and get costly quickly. 

- __Off Site Storage__: First time accession fees apply to all individual items stored off site. For instance, if Wolbach sent off site 108 items, a $1.26 charge per item would be applied resulting in a $136.08 charge. Each time an item is recalled to Wolbach, a courier is used with recall fees totalling $3.27 per item. As a result, while complex decisions are made regarding what materials to send off-site. the most substantial deciding factor is library space. Turn around time for the delivery of material is typically one to two business days, but if material is needed immediately, "emergency" recalls can be made a price of $182 per trip. It is therefore advantageous to limit the amount of material stored off site whenever possible. For fiscal year 2017, Wolbach has budgeted $31.5K for off-site storage. There are currently over 10.7 million items at the off site Depository used by Wolbach, and Harvard is exanding its off-site storage to accomodate an even larger amount of material.

# Literature Review

Our literature review focused on identifying applicable simulation strategies from the fields of library science and Monte Carlo simulation. Within the field of library science there are established methods and guidelines for shelf shifting [2] or adding shelving to libraries [3] and even for completely rearranging library spaces to accomodate more books [4]. However, estimating the amount of space to leave empty on a shelf for purposes of minimizing shelf shifts is somewhat imprecise. For example, documents and tools exist for estimating shelf space, time, and resources needed to shift a known collection [5] and there have been methods developed to inform decisions about shifting collections off site for the re-organization of a library [6]. In fact there are even commercial products available to help libraries with large collections move to new building; for expanding existing shelving; for moving to entirely new locations; and for shifting books to more evenly distribute space within existing shelving [7]. However, there appear to be no specific tools available for estimating the ideal amount of shelf space to leave open for purposes of minimizing the need for shelf shifts and maximizing the number of volumes kept on site. There seem to be no known applications of simulation for these puposes either. Many libraries develop their own ad-hoc approaches to estimating collection growth rates (note: ad-hoc growth rates are generally only applicable to periodical collections) or fall back on rules-of-thumb. For instance, there are numerous anecdotal references online to the general idea that one should leave at least 6 inches of space open on each shelf, but anecdotes do not appear to be based on any type of mathematical or scientific analysis. Instead, it is common industry practice to leave space for at least one human hand width at each end of a shelf when shifting.

The specific monte carlo simulation strategies...

insert articles [8 and 9] about monte carlo -- do you think it's appropriate to site the book or just articles? We need a few more I think.

# Methodology

As stated in the __Introduction__, our research was focused on attempting to answer the following question:

- What is the ideal amount of space to leave empty on a book shelf to minimize the need to shift and to accomodate the largest possible quantity books?

To address this question a Monte Carlo simulation of a small 1,000 volume library collection was developed using __R__. The simulation model relies on a variety of assumptions and constraints, each of which is described below. The assumptions and constraints are based on generalized metrics gathered relative to Wolbach Library's physical collection, community, and practices. For the purposes of building an easy to adapt proof-of-concept tool, the collection is substantially simplified. Each of the assumptions listed below can be adjusted to accomodate differing parameters within different library contexts.

### Assumptions

- __Number of Books/Volumes__: The simulated library collection is comprised of a total of 1,000 books. This represents a single, relatively small, collection within the broader library collection.

- __Types of Books/Volumes__: There are two types of books in the simulation: textbooks and non-textbooks. 5% of the collection is assumed to be master copies of textbooks at the start of the simulation. Multiple copies of a textbook are typically housed within the library; e.g., multiple copies of new physical textbooks are routinely purchased for the small number of undergraduate Astronomy courses taught each semester at the Harvard-Smithsonian Center for Astrophysics, and duplication of textbooks is typical within any given subsection of the library. Within the simulation, the number of copies of a textbook is determined by randomly sampling from a uniform distribution bounded by (1, 3). By contrast, non-textbooks are generally not duplicated within the library.

- __Book Widths__: The width of the simulated books varies between 1 and 2 inches according to a triangular approximation of a normal distribution. As such, when a book is added to the library a random sample from a triangular (1, 2) bound distribution is used to determine the width of that book. This distribution is based on architectual graphics standards used in library space design [10]. By defaulting to these standards the simulated library collection does not need to distinguish between paperback and hardcover volumes.

- __Shelves__: A total of fifty (50) 36 inch shelves are available for storage of the simulated library collection. Books are assigned to the simulated shelves in a serial manner at the start of the simulation until a user-specified minimum amount of free space remains on a given shelf. Once that minimum amount is achieved, shelving continues on the next available shelf. Any volumes not shelvable due to space constraints are sent "off-site" for the purposes of the simulation. The total number of shelves (50) represents the typical amount of shelving designated for a small subcollection within Wolbach Library.

- __Books in Circulation__: We assume that 10% of the total collection has been checked out for use by various library patrons prior to the start of the simulation. This value is a simplified assumption based on averages of monthly "COUNTER" statistics pulled from Harvard's __Cognos__ reporting tool for Wolbach's non-periodical collection and could be modified for any specific collection's circulation rate. Collection circulation rates tend to be seasonal in nature and are not typically tracked at the level of a subcollection. The width of any book that is in circulation is added back to the amount of free space available on the relevant shelf.

- __Percentage of Books Weeded__: Wolbach Library's general collection development policy is in the process of being reassessed, however, a general plan is in place to begin executing a regular weeding policy. The simulation reflects that policy in that 2% of the simulated collection is flagged for weeding during each round of the simulation. If a book is checked out at the time weeding it is considered exempt from weeding for that round of the simulation. This is done to ensure circulating books are not weeded. 

- __Number of Textbooks De-Duplicated__: We determine the number of textbooks to be de-duplicated during each round of the simulation by sampling from a uniform (1,5) bound distribution. A corresponding number of textbooks is then randomly selected from the simulated collection for de-duplication. During de-duplication, all copies of the selected textbooks are removed from the collection. However, a master copy is retained. If a copy of a textbook is flagged for de-duplication while it is in circulation, it is not immediately removed from the simulated collection but instead is flagged for removal when it is returned to the library.

- __Percentage of Books Checked In__: We assume that 20% of books currently in circulation are returned to the library during each round of the simulation. Books to be checked back in are selected via simple random sampling of the books currently in circulation.

- __Percentage of Books Checked Out__: We assume that 2% of books currently __not__ in circulation are randomly selected for check out during each round of the simulation.

- __New Textbook Acquisitions__: We assume that between 3 and 6 new textbooks and associated copies will be added to the collection during each round of the simulation. The number of copies to be added to the master copy for each new textbook purchased is determined by sampling from a uniform (1,3) bound distribution. Non-full shelves are randomly selected for each new textbook and associated copies are colocated on the same shelf.

- __New Non-Textbook Acquisitions__: We assume that between 5 and 26 new non-textbooks are added to the collection during each round of the simulation. Random selection of non-full shelves is used to shelve the new non-textbooks.

- __Amount of Initial Free Shelf Space__: The simulation examines a series of initial free shelf space values ranging from 3 inches up to 6 inches in 0.5 inch increments. The amount of initial free shelf space is used during shelving of the virtual library collection at the start of each round of the simulation, with each of the 50 shelves guaranteed to have no less than the indicated amount of free space. 

- __Shelf Filling__: A shelf is considered "full" if at least 95% of its available space has been consumed. When a shelf surpasses 95% use, no further new textbook acquisitions may be added to that shelf. However, books from such a shelf that are in circulation when the 95% usage bound is surpassed are returned to the shelf whenever they are returned to the library.

- __Shelf Shift Required__: A shelf shift is assumed to be required whenever at least 5 shelves achieve "full" status.

### Running the Simulation

The R-based simulation allows us to evaluate the effects of a variety of initial free space values. Specifically, the R code implements and aggregates the results of 100 simulations for each of the initial free shelf space values of 3, 3.5, 4, 4.5, 5, 5.5, and 6 inches. A single run of the simulation is deemed to be complete whenever at least 5 library shelves become "full" according to the __Shelf Filling__ description given above. The results of the simulations for the various initial free shelf space values are then tabulated and compared to allow us to determine which of the initial free shelf space value yields allows for the smallest average number of shelf shifts for the given 1,000 volume collection while sending as few books as possible to off-site storage.

__Overview of Simulation Logic__:    
Simple flow chart of simulation for clarity?   

__Model Validation__:

- subjective test: SME (i.e., Daina)

- build model with high face validity

- validate model assumptions (SME again)

- Potential user involved in model construction from conceptualization through implementation

# Results

[insert box plot, results table with titles and axes lables]
Discussion

# Summary and Future Works

The purpose of our research was to attempt to ...

It is important to note that these conclusions apply *only* to ...


# References

[1] http://library.cfa.harvard.edu/

[2] https://www.libraries.rutgers.edu/rul/staff/access_serv/coll_mgt/overview_of_shifting.pdf

[3] https://scholarsbank.uoregon.edu/xmlui/bitstream/handle/1794/12208/Moving+Library+Collections_+UO+Libraries2.pdf?sequence=1

[4] http://www.tandfonline.com/doi/abs/10.1300/J105v05n01_07

[5] https://osc.hul.harvard.edu/liblab/projects/collection-shift-estimation-visualization-tool

[6] http://www.tandfonline.com/doi/abs/10.1080/01462679.2016.1212755

[7] http://www.aautomate.com/products/shelf-space-manager

[8] Paxton, Pamela, et al. "Monte Carlo experiments: Design and implementation." Structural Equation Modeling 8.2 (2001): 287-312.

[9] Homem-de-Mello, Tito, and G?zin Bayraksan. "Monte Carlo sampling-based methods for stochastic optimization." Surveys in Operations Research and Management Science 19.1 (2014): 56-85.

[10] https://www.graphicstandards.com/

__--------------------------------------------------------------------------------------------------------------------------__

\newpage


# Appendix

This Appendix contains the research results, source R code, and associated relevant output from our final writeup and our simulation efforts. Additional supplemental graphics and detailed explanations of our simulation efforts are also included.

__--------------------------------------------------------------------------------------------------------------------------__

